# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']


# Numpy

In [6]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 5. Create an array of all the even integers from 20 to 35

In [9]:
np.arange(20,36,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd


In [14]:
jan = pd.date_range(start='2021-01-01', end='2021-01-31')

data = {
  "registered": [5, 4, 3, 4, 3, 5, 1, 6, 1, 9, 5, 3, 7, 2, 8, 4, 4, 6, 4, 3, 2, 5, 3, 4, 2, 6, 8, 5, 3, 4, 5]
}
df = pd.DataFrame(data, index=jan)

print(df.first('5D'))

            registered
2021-01-01           5
2021-01-02           4
2021-01-03           3
2021-01-04           4
2021-01-05           3


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [16]:
from dateutil.parser import parse
date_series = pd.Series(['1 Jan 2023', '10 Feb 2023'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('11 ' + d))
print(result)

Original Series:
0     1 Jan 2023
1    10 Feb 2023
dtype: object

New dates:
0   2011-01-01 20:23:00
1   2011-02-10 20:23:00
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [17]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
df = pd.DataFrame(lists, columns =['FName', 'LName', 'Age'],
                                           dtype = float) 
print(df)

   FName LName   Age
0    1.0   aaa  22.0
1    2.0   bbb  25.0
2    3.0   ccc  24.0


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)
